[versions]
kotlin = "2.2.21"
clikt = "5.0.3"
mordant = "3.0.2"
korim = "4.0.10"

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "mordant" }
mordant-coroutines = { module = "com.github.ajalt.mordant:mordant-coroutines", version.ref = "mordant" }
korlibs-korim = { module = "com.soywiz.korlibs.korim:korim", version.ref = "korim" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }